//练习12：（3）以一个所有位都为1的二进制数字开始，先左移它，然后用无符号右移操作符对其进行右移，直至所有的二进制位都被移出为止。每移一位都要使用Integer.toBinaryString()显示结果。
import static net.mindview.util.Print.*;

public class E12_UnsignedRightShift {
    public static void main(String[] args) {
        int i = -1 << 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
        i >>>= 1;
        print(Integer.toBinaryString(i));
    }
}